# Generated by Django 4.2.20 on 2025-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_uploadeddocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='references',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processed_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
