# Generated by Django 4.2.20 on 2025-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_questionanswer_references_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='processed_chunks',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='text_metadata',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
