# Generated by Django 4.2.20 on 2025-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_rename_uploaded_at_uploadeddocument_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='source_text',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='text_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
